#ifndef CONFIG_H
#define CONFIG_H

#define INTERVAL_NANOSECONDS 50000
#define LATENCY_GROUPING 256
#define ENTRY_COUNT 256
#define SEGMENT_COUNT 512
#define QUEUE_DEPTH 512

#define RECEIVER_PORT 8329

#define THREAD_NUMBER_MAIN 0
#define THREAD_NUMBER_CLIENT 1
#define THREAD_NUMBER_SERVER 2

#endif
